apiVersion: v1
kind: Pod
metadata:
 name: test-mysql
 labels:
   name: test-mysql
spec:
 containers:
   - resources:
       limits:
         cpu: 0.5
     image: mysql:5.6
     name: test-mysql
     env:
       - name: MYSQL_ROOT_PASSWORD
         value: root
       - name: MYSQL_DATABASE
         value: weather
     ports:
       - containerPort: 3306
         name: test-mysql
     volumeMounts:
         # This name must match the volumes.name below.
       - name: mysql-persistent-storage
         mountPath: /var/lib/mysql
 volumes:
   - name: mysql-persistent-storage
     gcePersistentDisk:
       # This disk must already exist.
       pdName: mysql-disk
       fsType: ext4