apiVersion: v1
kind: Pod
metadata:
 name: test-webapp
 labels:
   name: test-webapp
spec:
 containers:
   - image: gcr.io/steady-syntax-162706/webapp-image
     name: test-webapp
     ports:
       - containerPort: 80
         name: test-webapp